name: test_banking

on:
  workflow_dispatch:


jobs:
  banking:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: update
      run:  |
        git submodule update --init --recursive
        sudo apt install lcov
        sudo apt install g++
    - name: build banking
      shell: bash
      run: |
        cd lab_5/banking
        mkdir build && cd build
        cmake ..
        cmake --build .
    - name: test banking
      run: |
        cd lab_5
        mkdir build && cd build
        CXX=/usr/bin/g++
        cmake -DCOVERAGE=1 ..
        cmake --build .
        ./test
        lcov -t "banking" -o lcov.info -c -d .
        lcov --remove lcov.info '/home/runner/work/TIMP/TIMP/lab_5/third-party/GTest/*' -o lcov.info ###
        lcov --remove lcov.info '/usr/include/*' -o lcov.info

    - name: CovBeg
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel: true
        path-to-lcov: ./lab_5/build/lcov.info
        coveralls-endpoint: https://coveralls.io

    - name: CovFin
      uses: coverallsapp/github-action@master
      with:
       github-token: ${{ secrets.github_token }}
       parallel-finished: true
